# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PredictMoistureUpper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ts: str=None, value: float=None):  # noqa: E501
        """PredictMoistureUpper - a model defined in Swagger

        :param ts: The ts of this PredictMoistureUpper.  # noqa: E501
        :type ts: str
        :param value: The value of this PredictMoistureUpper.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'ts': str,
            'value': float
        }

        self.attribute_map = {
            'ts': 'ts',
            'value': 'value'
        }
        self._ts = ts
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'PredictMoistureUpper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictMoisture_upper of this PredictMoistureUpper.  # noqa: E501
        :rtype: PredictMoistureUpper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ts(self) -> str:
        """Gets the ts of this PredictMoistureUpper.


        :return: The ts of this PredictMoistureUpper.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this PredictMoistureUpper.


        :param ts: The ts of this PredictMoistureUpper.
        :type ts: str
        """

        self._ts = ts

    @property
    def value(self) -> float:
        """Gets the value of this PredictMoistureUpper.


        :return: The value of this PredictMoistureUpper.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this PredictMoistureUpper.


        :param value: The value of this PredictMoistureUpper.
        :type value: float
        """

        self._value = value
