# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SoilMoisture(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, read_time: str=None, soil_moisture: float=None):  # noqa: E501
        """SoilMoisture - a model defined in Swagger

        :param read_time: The read_time of this SoilMoisture.  # noqa: E501
        :type read_time: str
        :param soil_moisture: The soil_moisture of this SoilMoisture.  # noqa: E501
        :type soil_moisture: float
        """
        self.swagger_types = {
            'read_time': str,
            'soil_moisture': float
        }

        self.attribute_map = {
            'read_time': 'read_time',
            'soil_moisture': 'soil_moisture'
        }
        self._read_time = read_time
        self._soil_moisture = soil_moisture

    @classmethod
    def from_dict(cls, dikt) -> 'SoilMoisture':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SoilMoisture of this SoilMoisture.  # noqa: E501
        :rtype: SoilMoisture
        """
        return util.deserialize_model(dikt, cls)

    @property
    def read_time(self) -> str:
        """Gets the read_time of this SoilMoisture.


        :return: The read_time of this SoilMoisture.
        :rtype: str
        """
        return self._read_time

    @read_time.setter
    def read_time(self, read_time: str):
        """Sets the read_time of this SoilMoisture.


        :param read_time: The read_time of this SoilMoisture.
        :type read_time: str
        """

        self._read_time = read_time

    @property
    def soil_moisture(self) -> float:
        """Gets the soil_moisture of this SoilMoisture.


        :return: The soil_moisture of this SoilMoisture.
        :rtype: float
        """
        return self._soil_moisture

    @soil_moisture.setter
    def soil_moisture(self, soil_moisture: float):
        """Sets the soil_moisture of this SoilMoisture.


        :param soil_moisture: The soil_moisture of this SoilMoisture.
        :type soil_moisture: float
        """

        self._soil_moisture = soil_moisture
