openapi: 3.0.0
info:
  title: Real-Time soil moisture level.
  description: TBA
  version: 0.0.1
servers:
- url: /moisture/v1
paths:
  /sensor/latest:
    get:
      summary: Returns the latest sensor readings (light, temperature, soil moisture).
      operationId: controller.get_latest_sensor_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
  
  /sensor/aggregate:
    parameters:
      - in: query
        name: days
        schema:
          type: integer
      - in: query
        name: hours
        schema:
          type: integer

    get:
      summary: Returns a list of average sensor readings of every user-specified interval for the last user-specified days.
      operationId: controller.aggregate_sensor_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'
  /weather/latest:
    get:
      summary: Returns the latest weather data from open-meteo
      operationId: controller.get_latest_weather_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherData'
  
  /weather/aggregate:
    parameters:
      - in: query
        name: days
        schema:
          type: integer
      - in: query
        name: hours
        schema:
          type: integer
    get:
      summary: Returns a list of average sensor readings of every user-specified interval for the last user-specified days.
      operationId: controller.aggregate_weather_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherData'
  /predictmoisture/{moisture}:
    parameters:
    - name: moisture
      in: path
      required: true
      schema:
        type: number
    get:
      summary: Get the prediction of soil moisture.
      operationId: controller.moisture_prediction
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictMoisture'

components:
  schemas:
    SensorData:
      type: object
      properties:
        read_time:
          type: string
        light:
          type: number
        temperature:
          type: number
        soil_moisture:
          type: number
    WeatherData:
      type: object
      properties:
        read_time:
          type: string
        humidity:
          type: number
        precipitation:
          type: number
        temperature:
          type: number
        cloud_cover:
          type: number
    SoilMoisture:
      type: object
      properties:
        read_time:
          type: string
        soil_moisture:
          type: number
    PredictMoisture:
      type: object
      properties:
        duration:
          type: string
        old_data:
          type: array
          items:
            $ref: '#/components/schemas/SoilMoisture'
        predictions:
          type: array
          items:
            $ref: '#/components/schemas/SoilMoisture'
        upper:
          type: array
          items:
            $ref: '#/components/schemas/SoilMoisture'
        lower:
          type: array
          items:
            $ref: '#/components/schemas/SoilMoisture'
