openapi: 3.0.0
info:
  title: Real-Time soil moisture level.
  description: TBA
  version: 0.0.1
servers:
- url: /moisture/v1
paths:
  /sensor/latest:
    get:
      summary: Returns the latest sensor readings (light, temperature, soil moisture).
      operationId: controller.get_latest_sensor_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
  /sensor/aggregateHour/{hrs}:
    parameters:
      - name: hrs
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns a list of average sensor readings every n hours where n is specified by the user.
      operationId: controller.get_aggregate_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'

components:
  schemas:
    SensorData:
      type: object
      properties:
        readTime:
          type: string
        light:
          type: number
        temperature:
          type: number
        soilMoisture:
          type: integer