openapi: 3.0.0
info:
  title: Real-Time soil moisture level.
  description: TBA
  version: 0.0.1
servers:
- url: /moisture/v1
paths:
  /sensor/latest:
    get:
      summary: Returns the latest sensor readings (light, temperature, soil moisture).
      operationId: controller.get_latest_sensor_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
  
  /sensor/aggregate:
    parameters:
      - in: query
        name: days
        schema:
          type: integer
      - in: query
        name: hours
        schema:
          type: integer

    get:
      summary: Returns a list of average sensor readings of every user-specified interval for the last user-specified days.
      operationId: controller.aggregate_sensor_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'
  /weather/latest:
    get:
      summary: Returns the latest weather data from open-meteo
      operationId: controller.get_latest_weather_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherData'
  
  /weather/aggregate:
    parameters:
      - in: query
        name: days
        schema:
          type: integer
      - in: query
        name: hours
        schema:
          type: integer
    get:
      summary: Returns a list of average sensor readings of every user-specified interval for the last user-specified days.
      operationId: controller.aggregate_weather_data
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherData'

components:
  schemas:
    SensorData:
      type: object
      properties:
        readTime:
          type: string
        light:
          type: number
        temperature:
          type: number
        soilMoisture:
          type: number
    WeatherData:
      type: object
      properties:
        readTime:
          type: string
        humidity:
          type: number
        precipitation:
          type: number
        temperature:
          type: number
        cloudCover:
          type: number